{% set name = "profilehooks" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54a541cad49ddccee97b61a617404d7d736bf0bf79d36fbe2ac7caa3a1d9daaf

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip >=22.3
    - python >=3.7
    - setuptools <66.0.0
  run:
    - python >=3.7

test:
  imports:
    - profilehooks

about:
  home: https://mg.pov.lt/profilehooks/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Decorators for profiling/timing/tracing individual functions
  doc_url: https://mg.pov.lt/profilehooks/
  dev_url: https://github.com/mgedmin/profilehooks

extra:
  recipe-maintainers:
    - YYYasin19
    - CJ-Wright
