{% set name = "profilehooks" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05b87589df8a8c630fd701bae6008cc1cfff4457bd0064887ad25248327a5ba3

build:
  noarch: python
  number: 3
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - profilehooks

about:
  home: https://mg.pov.lt/profilehooks/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Decorators for profiling/timing/tracing individual functions
  doc_url: https://mg.pov.lt/profilehooks/
  dev_url: https://github.com/mgedmin/profilehooks

extra:
  recipe-maintainers:
    - YYYasin19
    - CJ-Wright
